#!/usr/bin/env bash
# Group visitors by IP and HTTP status code, sorted by occurrence count descending
awk '{print $1 " " $9}' apache-access.log 2>/dev/null | sort | uniq -c | sort -nr | awk '{printf "    %d %s %s\n",$1,$2,$3}'
