#!/usr/bin/env bash
# Groups visitors by IP and HTTP status code, and displays this data sorted by number of occurrences

awk '{print $1, $9}' apache-access.log 2>/dev/null | sort | uniq -c | sort -nr | awk '{printf "    %s %s %s\n", $1, $2, $3}'
