#!/usr/bin/env bash
# 14-dig_the-data: group by IP + HTTP code and sort by occurrences descending
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{printf "    %d %s %s\n", $1, $2, $3}'
