#!/usr/bin/env bash
# Script that creates a PID file and handles signals

echo "$$" > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' INT
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit' TERM
trap 'rm /var/run/myscript.pid; exit' QUIT

while true
do
    echo "To infinity and beyond"
    sleep 1
done
